permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  COLORTERM: "truecolor"

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / test
    strategy:
      matrix:
        toolchain: [ stable ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo test
        run: cargo test --workspace --all-features
